-- AlterTable
ALTER TABLE "Loan" ADD COLUMN "loyaltyTier" TEXT NOT NULL DEFAULT 'STANDARD',
ADD COLUMN "discountBps" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "ApplicationTerms" ADD COLUMN "loyaltyTier" TEXT NOT NULL DEFAULT 'STANDARD',
ADD COLUMN "discountBps" INTEGER NOT NULL DEFAULT 0;
